name: rgan_pytorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10.8
  - jupyter=1.0.0
  - numpy=1.23.5
  - matplotlib=3.6.2
  - seaborn=0.12.2
  - scipy=1.11.1
  - scikit-learn=1.3.0
  - pytorch::pytorch=1.13.1
  - conda-forge::pytorch-lightning==1.9.3
  - pip
  - pip:
    - -e .